import type { Metadata, Viewport } from "next";
// 🟢 1. CẬP NHẬT IMPORT FONT
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import NutHoTro from "@/app/components/NutHoTro";
import TuVanKhachHang from "@/app/components/TuVanKhachHang";
import ForceFullScreen from "@/app/components/ForceFullScreen";
import PushManager from "@/app/components/PushManager";
import QueryProvider from "@/app/QueryProvider";
import { UserProvider } from "@/app/ThuVien/UserContext";
import { AppSettingsProvider } from "@/app/ThuVien/AppSettingsContext";
import ErrorBoundary from "@/app/components/ErrorBoundary";

// 🟢 2. CẤU HÌNH FONT INTER (SANS)
const inter = Inter({
  subsets: ["latin", "vietnamese"], // Thêm vietnamese
  display: "swap",
  variable: "--font-inter",
});

// 🟢 3. CẤU HÌNH FONT PLAYFAIR DISPLAY (SERIF)
const playfair = Playfair_Display({
  subsets: ["latin", "vietnamese"], // Thêm vietnamese
  display: "swap",
  variable: "--font-playfair",
  weight: ["400", "500", "600", "700", "800", "900"], // Nạp đủ độ đậm
});

export const metadata: Metadata = {
  title: "Hệ Thống Quản Lý ERP",
  description: "Generated by Tommy Nghiem",
  manifest: "/manifest.json",
  icons: {
    icon: "/icon-192.png",
    shortcut: "/icon-192.png",
    apple: "/icon-192.png",
    other: {
      rel: "apple-touch-icon-precomposed",
      url: "/icon-192.png",
    },
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "NghiemArt ERP",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
  themeColor: "#000000",
  interactiveWidget: "resizes-visual",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      {/* 🟢 4. ÁP DỤNG BIẾN FONT VÀO BODY */}
      {/* Thay inter.className bằng chuỗi biến variable */}
      <body
        className={`${inter.variable} ${playfair.variable} bg-black min-h-screen overflow-hidden overscroll-none font-sans`}
      >
        <UserProvider>
          <AppSettingsProvider>
            <QueryProvider>
              <ErrorBoundary>
                <ForceFullScreen />
                {children}

                <NutHoTro />
                <TuVanKhachHang />
                <PushManager />
              </ErrorBoundary>
            </QueryProvider>
          </AppSettingsProvider>
        </UserProvider>
      </body>
    </html>
  );
}
