import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import './globals.css'; 
import NutHoTro from '@/app/components/NutHoTro';
import TuVanKhachHang from '@/app/components/TuVanKhachHang'; // 🟢 MỚI: Import nút của nhân viên
import ForceFullScreen from '@/app/components/ForceFullScreen';
// 🟢 IMPORT REACT QUERY PROVIDER
import QueryProvider from '@/app/QueryProvider';
// 🟢 IMPORT USER PROVIDER
import { UserProvider } from '@/app/ThuVien/UserContext';
// 🟢 IMPORT APP SETTINGS PROVIDER (Theme + Language)
import { AppSettingsProvider } from '@/app/ThuVien/AppSettingsContext';
// ✅ IMPORT ERROR BOUNDARY
import ErrorBoundary from '@/app/components/ErrorBoundary';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Hệ Thống Quản Lý ERP',
  description: 'Generated by Tommy Nghiem',
  manifest: '/manifest.json',
  
  // Cấu hình Icon chuẩn
  icons: {
    icon: '/icon-192.png',
    shortcut: '/icon-192.png',
    apple: '/icon-192.png',
    other: {
      rel: 'apple-touch-icon-precomposed',
      url: '/icon-192.png',
    },
  },

  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'ArtSpace ERP',
  },
};

// 🟢 FIX CẤU HÌNH VIEWPORT CHO SAMSUNG INTERNET & TABLET
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  minimumScale: 1, // Ngăn thu nhỏ
  maximumScale: 1, // Ngăn phóng to
  userScalable: false,
  viewportFit: 'cover',
  themeColor: '#000000',
  interactiveWidget: 'resizes-visual',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      <body className={`${inter.className} bg-black min-h-screen overflow-hidden overscroll-none`}>
        {/* 🟢 BỌC USER PROVIDER CHO HỆ THỐNG AUTH */}
        <UserProvider>
          {/* 🟢 BỌC APP SETTINGS PROVIDER CHO THEME + LANGUAGE */}
          <AppSettingsProvider>
            <QueryProvider>
              <ErrorBoundary>
                <ForceFullScreen />
                {children}  
                
                {/* 🟢 NÚT HỖ TRỢ CHO KHÁCH HÀNG (Góc Trái) */}
                <NutHoTro />

                {/* 🟢 NÚT TƯ VẤN CHO NHÂN VIÊN (Tự ẩn nếu là khách) */}
                <TuVanKhachHang />

              </ErrorBoundary>
            </QueryProvider>
          </AppSettingsProvider>
        </UserProvider>
      </body>
    </html>
  );
}