import type { Metadata, Viewport } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";

// Components
import NutHoTro from "@/app/components/NutHoTro";
import TuVanKhachHang from "@/app/components/TuVanKhachHang";
import ForceFullScreen from "@/app/components/ForceFullScreen";
import PushManager from "@/app/components/PushManager";
import ErrorBoundary from "@/app/components/ErrorBoundary";

// Providers
import QueryProvider from "@/app/QueryProvider";
import { UserProvider } from "@/app/ThuVien/UserContext";
import { AppSettingsProvider } from "@/app/ThuVien/AppSettingsContext";

const inter = Inter({
  subsets: ["latin", "vietnamese"],
  display: "swap",
  variable: "--font-inter",
});

const playfair = Playfair_Display({
  subsets: ["latin", "vietnamese"],
  display: "swap",
  variable: "--font-playfair",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Hệ Thống Quản Lý ERP",
  description: "Generated by Tommy Nghiem",
  manifest: "/manifest.json",
  icons: {
    icon: "/icon-192.png",
    shortcut: "/icon-192.png",
    apple: "/icon-192.png",
    other: {
      rel: "apple-touch-icon-precomposed",
      url: "/icon-192.png",
    },
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "NghiemArt ERP",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
  themeColor: "#000000",
  interactiveWidget: "resizes-visual", // Giúp bàn phím ảo không che input
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      <body
        className={`${inter.variable} ${playfair.variable} bg-black h-app w-full overflow-hidden font-sans`}
      >
        <UserProvider>
          <AppSettingsProvider>
            <QueryProvider>
              <ErrorBoundary>
                {/* 1. Xử lý chiều cao & Fullscreen cho Mobile PWA */}
                <ForceFullScreen />

                {/* 2. Nội dung chính của trang (Page) */}
                {children}

                {/* 3. Các thành phần Fixed (Nổi trên cùng) */}
                {/* NutHoTro: Góc Phải (Khách hàng) */}
                <NutHoTro />

                {/* TuVanKhachHang: Góc Trái (Nhân viên) */}
                <TuVanKhachHang />

                {/* PushManager: Xử lý đăng ký nhận thông báo ngầm */}
                <PushManager />
              </ErrorBoundary>
            </QueryProvider>
          </AppSettingsProvider>
        </UserProvider>
      </body>
    </html>
  );
}
